// IMPORTANT! File generated by /home/jozsef/projects/hyperWiki/install.sh
/* eslint-disable */
const config = {
	ENDPOINT_CHILDREN: "topic/children/",
	ENDPOINT_PAGE: "page/",
	ENDPOINT_SEARCH: "info/search",
	HOST: "32.215.159.32",
	ORIGIN: "https://32.215.159.32:8020/",
	PORT: "8020",
	DEBUG_LEVEL:"trace",
	URL_CHILDREN: "https://32.215.159.32:8020/topic/children/",
	URL_PAGE: "https://32.215.159.32:8020/page/",
	URL_SEARCH: "https://32.215.159.32:8020/info/search",
	URL_USER_ADD: "https://32.215.159.32:8010/user/add/",
	URL_USER_AUTHINTICATE: "https://32.215.159.32:8010/user/authinticate/",
	URL_USER_GET: "https://32.215.159.32:8010/user/get/",
	URL_USER_LOGIN: "https://32.215.159.32:8010/user/login/",
	URL_USER_RESET: "https://32.215.159.32:8010/user/reset/password/",
	URL_USER_UPDATE: "https://32.215.159.32:8010/user/update/",
	URL_USER_UPDATE_PASSWORD: "https://32.215.159.32:8010/user/update/password/",
	WEB_SOCKET_URL: "ws://32.215.159.32:8030/topic/"
	DEBUG_LEVEL:"error",
};

exports.config = config;
